### ISSUE TITLE
Soccer not working correctly

### ISSUE THREAD

**Issue by plattyfish** [md-arif-shaikh/soccer#13]
Hi Md Arif

You helped me get things working some time ago I believe.

Now I don't think it is configured correctly.
I am not able to list Premier Leagues or get results of fixtures.

My configuration is as follws

;;for soccor

;;; bootstrap straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
	(url-retrieve-synchronously
	  "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	     'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;;; install use-package
(straight-use-package 'use-package)

(use-package soccer
:straight (soccer :type git :host github :repo "md-arif-shaikh/soccer"))

Hope you can help me get it all working again.

Regards James

**Comment by md-arif-shaikh** [comment]
Hi, there were some issues sometimes ago and we fixed that in the current version. Did you try pulling the package and reinstall using straight? You can do that from within Emacs. 
`M-x straight-pull-package` to pull recent changes and the rebuild `M-x straight-rebuild-package`

**Comment by plattyfish** [comment]
Hi Arif

Thank you,
This has worked.

Great work

Regards James Cobb

**Comment by plattyfish** [comment]
Many Thanks
