### ISSUE TITLE
emacs complains Symbol's function definition is void: use-package

### ISSUE THREAD

**Issue by plattyfish** [md-arif-shaikh/soccer#9]
Just installed soccer from Melpa
Copied full config to bottom of my .emacs file and I get the message when I launch emacs (27.1) on Lubuntu 22.04
If I try M-x soccer there are no entries to soccer.

Suggestions, please

Regards James

This is what I copied to my .emacs file

(use-package soccer
    :straight (soccer :type git :host github :repo "md-arif-shaikh/soccer")
    :init
    (setq soccer-leagues-alist
	      '(("England" . "Premier League")
		("Spain" . "Laliga")
		("France" . "Ligue 1")
		("Italy" . "Serie A")
		("Germany" . "Bundesliga")
		;;("uefa" . "Champions League")
		;;("England" . "Championship")
		))
    :config
    (setq soccer-time-local-time-utc-offset "+0530")
    :bind (("C-c s f" . soccer-fixtures-next)
	     ("C-c s r" . soccer-results-last)
	     ("C-c s s" . soccer-scorecard)
	     ("C-c s t" . soccer-table)))

**Comment by md-arif-shaikh** [comment]
Hi, can you try installing `straight` and `use-package` using the following code
```emacs-lisp
;;; bootstrap straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
	(url-retrieve-synchronously
	  "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
	     'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;;; install use-package
(straight-use-package 'use-package)
```

After that you should be able to install `soccer` from the source using
```emacs-lisp
(use-package soccer
:straight (soccer :type git :host github :repo "md-arif-shaikh/soccer")
````

**Comment by md-arif-shaikh** [comment]
I tried to build and use `soccer` using the above block of code on a new machine and it worked. So I expect it will work for you too. Let me know if you still have a problem. The original issue was that you did not have the package `straight` or `use-package` installed in your emacs, the above block of code does that for you.

**Comment by plattyfish** [comment]
Thank you, Arif-Shalkh 
I got it working now
Your code helped.

**Comment by plattyfish** [comment]
Hi Arif , Yes I got soccer working fine , I was getting some paren errors
but seemed to have sorted it out.

Thankyou for you help, I can now use soccer to keep score.

Regards James
